### ISSUE TITLE
cant install on colab

### ISSUE THREAD

**Issue by hadaev8** [szymonmaszke/torchfunc#6]
Collecting torchfunc
  ERROR: Could not find a version that satisfies the requirement torchfunc (from versions: none)
ERROR: No matching distribution found for torchfunc
https://colab.research.google.com/drive/1MUxPXhZiQ1Wt2EFIn7PLIy5FiHII-FsG

**Comment by szymonmaszke** [comment]
`torchfunc` needs Python with version `3.7` or above. Current version of Python on Google's Colab is `3.6.8`. 

The only way to run it is to connect `colab` to some local runtime of yours, see [here](https://research.google.com/colaboratory/local-runtimes.html). Either that or you have to wait for Python update provided by Google.

**Comment by hadaev8** [comment]
Thanks
